export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>MyProfile</title>
  <base href="/profile/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<style>body{font-family:Arial,sans-serif;margin:0;padding:0;background-color:#f8f9fa;color:#333}nav{background:#343a40;padding:15px;text-align:center}nav a{color:#fff;text-decoration:none;font-size:18px;margin:0 15px;transition:color .3s ease}nav a:hover{color:#f8d210}p{font-size:20px;color:#555;line-height:1.6}
</style><link rel="stylesheet" href="styles-7LRXK32R.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles-7LRXK32R.css"></noscript><style ng-app-id="ng">a[_ngcontent-ng-c1904238049]{pointer-events:auto!important;cursor:pointer!important}</style><style ng-app-id="ng">.contact-info[_ngcontent-ng-c2696222531]{font-family:Poppins,sans-serif;font-size:16px;color:#333;text-align:left}.contact-link[_ngcontent-ng-c2696222531]{color:#6a0dad;text-decoration:none;font-weight:600;transition:color .3s ease-in-out}.contact-link[_ngcontent-ng-c2696222531]:hover{color:indigo;text-decoration:underline}.contact-info[_ngcontent-ng-c2696222531]{display:flex;flex-direction:column;align-items:center;justify-content:center;height:100vh;text-align:center}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["click"],[]);</script>
  <app-root ng-version="19.2.4" _nghost-ng-c1904238049 ngh="1" ng-server-context="ssg"><nav _ngcontent-ng-c1904238049><a _ngcontent-ng-c1904238049 routerlink="/" routerlinkactive="active" href="/profile/" class="active" jsaction="click:;">About</a> | <a _ngcontent-ng-c1904238049 routerlink="/experience" routerlinkactive="active" href="/profile/experience" class jsaction="click:;">Experience</a> | <a _ngcontent-ng-c1904238049 routerlink="/skills" routerlinkactive="active" href="/profile/skills" class jsaction="click:;">Skills</a> | <a _ngcontent-ng-c1904238049 routerlink="/projects" routerlinkactive="active" href="/profile/projects" class jsaction="click:;">Projects</a> | <a _ngcontent-ng-c1904238049 routerlink="/contact" routerlinkactive="active" href="/profile/contact" class="active" jsaction="click:;">Contact</a></nav><router-outlet _ngcontent-ng-c1904238049></router-outlet><app-contact _nghost-ng-c2696222531 ngh="0"><div _ngcontent-ng-c2696222531 class="contact-info"><p _ngcontent-ng-c2696222531> Email: <a _ngcontent-ng-c2696222531 href="mailto:kunche.raju@gmail.com" classname="contact-link"> kunche.raju@gmail.com </a></p><p _ngcontent-ng-c2696222531> Phone: 9030110695 </p><p _ngcontent-ng-c2696222531><a _ngcontent-ng-c2696222531 href="https://www.linkedin.com/in/i_am_raju_kunche" target="_blank" rel="noopener noreferrer" classname="contact-link"> LinkedIn: </a></p><p _ngcontent-ng-c2696222531><a _ngcontent-ng-c2696222531 href="https://github.com/rkunche" target="_blank" rel="noopener noreferrer" classname="contact-link"> Github </a></p></div></app-contact><!----></app-root>
<script src="polyfills-FFHMD2TL.js" type="module"></script><script src="main-C42XFLL6.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{},{"c":{"15":[{"i":"c2696222531","r":1}]}}]}</script></body></html>`;